spring.application.name=food-store-api
spring.datasource.url=jdbc:h2:mem:foodstoredb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.prog3=DEBUG
logging.level.org.springframework.web=WARN

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=com.prog3.food_store_api.controllers

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

seed.admin.email=${SEED_ADMIN_EMAIL}
seed.admin.password=${SEED_ADMIN_PASSWORD}